src/Entity/Information.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InformationRepository")
 */
class Information
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=350, nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="information", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(?string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/Post.php
<?php
namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=350, nullable=true)
     */
    private $contenu;    
    
    /**
     * @ORM\Column(type="datetime")
     */
    private $datepost;    
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;    
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ImagePost", mappedBy="post")
     */
    private $image;    
    
    public function __construct()
    {
        $this->image = new ArrayCollection();
    }    
    
    public function getId(): ?int
    {
        return $this->id;
    }    
  
    public function getContenu(): ?string
    {
        return $this->contenu;
    }    
  
    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;          
        return $this;
    }    
  
    public function getDatepost(): ?\DateTimeInterface
    {
        return $this->datepost;
    }    
  
    public function setDatepost(\DateTimeInterface $datepost): self
    {
        $this->datepost = $datepost;        
        return $this;
    }    
  
    public function getUser(): ?User
    {
        return $this->user;
    }    
  
    public function setUser(?User $user): self
    {
        $this->user = $user;        
        return $this;
    }    
  
    /**
     * @return Collection|ImagePost[]
     */
    public function getImagePost(): Collection
    {
        return $this->image;
    }    
  
    public function addImagePost(ImagePost $image): self
    {
        if (!$this->image->contains($image)) {
            $this->image[] = $image;
            $image->setPost($this);
        }        return $this;
    }    
  
    public function removeImagePost(ImagePost $image): self
    {
        if ($this->image->contains($image)) {
            $this->image->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getPost() === $this) {
                $image->setPost(null);
            }
        }        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Entity\ImagePost;
use App\Repository\PostRepository;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profile", name="profile_show")
     * @Route("/profile/{id}", name="profile_show")
     */
    public function profile_show(UserRepository $userRepository, Request $request, PostRepository $postRepository, UserInterface $userInterface, $id = false)
    {
        $entityManager = $this->getDoctrine()->getManager();
        
        // création d'un utilisateur connecté pour différencier chaque post de chaque user
        $userConnect = $userInterface;

        if($id === false){
            $user = $this->getUser();
            $id = $user->getId();
        } else{
            $user = $userRepository->find($id);
        }

        // Instanciation d'un nouveau post
        $post = new Post();
        $form = $this->createForm(PostType::class, $post); // Création du formulaire
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            // récupération des données date et user_id 
            $date = new \DateTime();
            $post->setDatepost($date);
            $post->setUser($user);

            $files = $form->get('image')->getData();

            // Recuperation de l'image et traitement
            if ($files) {
                foreach ($files as $file) {
                    $imagePost = new ImagePost();

                    // Déplace le fichier dans le dossier où les images sont stockées
                    $newFilename ='img_' . uniqid().'.'.$file->guessExtension();

                    try {

                        $file->move(
                            $this->getParameter('images_directory'),
                            $newFilename
                        );

                    } catch (FileException $e) {

                        // ... handle exception if something happens during file upload

                    }   // updates the 'brochureFilename' property to store the jpg file name

                    // J'enregistrer dans le post et dans la base image
                    $imagePost->setImage($newFilename);
                    $imagePost->setPost($post);
                    $entityManager->persist($imagePost);
                    $post->addImagePost($imagePost);
                }
                
            }
            
            $entityManager->persist($post);

            // Ne peut pas rien envoyer soit une photo soit un contenu
            if(null != $post->getContenu() || !empty($file)){
               $entityManager->flush(); 
            }

            // renvoie vers la page profile pour raffraichir la page
            return $this->redirectToRoute('profile_show');
        }

        // Requete SQL
        $affichagePost = $postRepository->findAll();

        // recuperation des informations du formulaire information
        $userInformation = $user->getInformation();

        // Affichage des formulaire et des informations
        return $this->render('profile/index.html.twig', [
            'user' => $user,
            'information' => $userInformation,
            'addPost' => $form->createView(),
            'affichagePosts' => $affichagePost,
            'userConnect' => $userConnect
        ]);
    }

    /**
     * @Route("/profile/post-edit/{id}", name="post_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Post $post): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        // si on renvoie le formulaire de changement de post 
        // alors on le traite et on l'enregistre
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profile_show');
        }

        return $this->render('profile/edit.html.twig', [
            'post' => $post,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/profile/post-delete/{id}", name="post_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Post $post, UserInterface $userInterface): Response
    {

        // création d'une variable admin
        $hasAccess = $this->isGranted('ROLE_ADMIN');
        
        $user = $this->getUser();
        $userConnect = $userInterface;

        if ($userConnect == $user || $userConnect == $user["ROLE_ADMIN"]){

            // Si le jeton (token) ets valide, alors on demande la suppréssion du post correspondant
            if($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
                $entityManager = $this->getDoctrine()->getManager();

                // on enregistre une liste d'image
                $listImage = $post->getImagePost();

                // on boucle la suppression d'une collection d'image
                // Car les clés étrangères doivent être supprimer avant
                foreach($listImage as $image){
                    $post->removeImagePost($image);
                }

                // puis on supprime le post
                $entityManager->remove($post);
                $entityManager->flush();

                // message flash de suppression
                $message = $this->addFlash(
                    'notice',
                    'Votre post a été supprimé'
                );

                if($userConnect == $hasAccess){ // admin renvoyer vers la page admin
                    return $this->redirectToRoute('admin');
                } else { // si on est user on renvoie vers profile
                    return $this->redirectToRoute('profile_show');
                }
                
            }
        }
        return $this->render('profile/index.html.twig', [
            'message' => $message
        ]);
    }

}

templates/profile/_delete_form.html.twig
<form method="post" action="{{ path('post_delete', {'id': affichagePost.id}) }}" onsubmit="return confirm('Etes vous sur(e) ?');">
{# Modale de suppression #}
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ affichagePost.id) }}">
    <button class="btn btn-danger btn-block mb-2">Supprimer</button>{# affichage du bouton sur la vu #}
</form>

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition du Post
{% endblock %}

{% block body %}{# Edition du post #}
	<h1>Edit Post</h1>
	{{ form_start(form) }}
	{{ form_widget(form) }}
	{{ form_end(form) }}
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}

	<div class="text-center mb-3">
		<h1 class="profileTitle">Profile page</h1>
		{% for message in app.flashes('notice') %}

			<p>{{ message }}</p> {# Affichage du message flash de suppression #}

		{% endfor %}
	</div>

	<div class="container mb-4">

		<div class="row">

			<div class="col-md-4 col-sm-12 mb-2 centrage-profile bord-droit"> {# Affichage des informations d'inscription #}
				<p>{{ user.email }}<br>
			    {{ user.pseudo }}</p>{# Affichage de la possibilite d'une conversation #}
				<a href="{{ path('chat', {'id': user.id}) }}"><i class="fas fa-comments msgIcon banner"></i></a>
			</div>

			<div class="col-md-4 col-sm-12 mb-2 centrage-profile bord-droit">{# Affichage de la photo #}
				<img style="width:200px;height:200px;" src="{{ asset('uploads/image/' ~ user.image ) }}" alt="Image user's">
			</div>

			{% if user.information %}{# Affichage des informations complémentaires #}
				<div class="col-md-4 col-sm-12 centrage-profile">
					<p> <span class="font-weight-bold">Nom :</span>  {{ user.information.nom }}<br>
						<span class="font-weight-bold">Prénom :</span>  {{ user.information.prenom }}<br>
						<span class="font-weight-bold">Date de naissance :</span>  {{ user.information.dateNaissance|date("d-m-Y") }}<br>
						<span class="font-weight-bold">Adresse :</span>  {{ user.information.adresse }}<br>
						<span class="font-weight-bold">Ville :</span>  {{ user.information.ville }}<br>
						<span class="font-weight-bold">Code Postal :</span>  {{ user.information.cp }}<br>
					</p>
				</div>
			{% endif %}
		</div>
	</div>

	<div class="col-12 text-center">
		{% if user.information %}{# Afficher et centrer la description #}
			<p>Description:<br>
			<q><i> {{ user.information.description }} </i></q></p>
		{% endif %}
	</div>
	
	{% if userConnect == user %}{# empeche n'importe qui de poster à la place de l'utilisateur #}

		<div class="container">{# Affichage formulaire post #}
			<button onclick="myDisplay()" class="btn btn-warning mb-2">+</button>
			<div id="toggle-post">
				{{ form_start(addPost) }}
					{{ form_row(addPost.image) }}
					{{ form_row(addPost.contenu) }}
				{{ form_end(addPost) }}
			</div>
		</div>

	{% endif %}

	<div class="afficher-post-entier ">
		{% if affichagePosts %} 

			{% for affichagePost in affichagePosts %}{# Boucle pour post #}

				{% if affichagePost.user == user %}{# afficher les postes de l'utilisateur #}

					<div class="container rounded border bg-dark text-light mb-3">

						<div class="row p-3">
							<img class="pr-2" style="width:50px;height:50px;" src="{{ asset('uploads/image/' ~ user.image ) }}" alt="Image utilisateur">
							<p class="colorPseudo">{{ user.pseudo }}</p>
						</div>

						{% for image in affichagePost.imagePost %} {# Affichage des images #}

							<img style="width:100px;height:100px;" src="{{ asset('uploads/image/' ~ image.image ) }}" alt="">

						{% endfor %}

						<div class="row">

							<div class="container contenuAntiDebordement col-8"> {# Affichage du contenue et de la date #}
								<p>{{ affichagePost.contenu }}</p>
								<small>{{ affichagePost.datepost|date("d-m-Y H:i:s") }}</small>
							</div>

							{% if userConnect == user %}{# Seul l'utilisateur peut modifier son post #}
								<div class="container col-4 d-flex flex-column justify-content-around">
									<a class="btn btn-warning btn-block mb-1" href="{{ path('post_edit', {'id': affichagePost.id}) }}">Modification</a>
							{% endif %}
							{% if userConnect == user or is_granted('ROLE_ADMIN') %}{# Si l'utilisateur est le celui qui post ou si il y est admin #}
									{% include 'profile/_delete_form.html.twig' %}{# Alors on peut supprimer #}
								</div>
							{% endif %}

						</div>

					</div>

				{% endif %}

			{% endfor %}

		{% endif %}
	</div>

	<div class="animLoad">
	
	</div>

	{% block additionnalJS %}{# Javascript additionnel #}

		<script src="{{ asset('js/post.js') }}"></script>

	{% endblock %}

{% endblock %}