src/Entity/Message.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", length=350, nullable=true)
     */
    private $contenu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_envoi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userReceiver;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messageSender")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userSender;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Conversation", inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $conversation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ImageChat", mappedBy="message")
     */
    private $imageChats;

    public function __construct()
    {
        $this->imageChats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateEnvoi(): ?\DateTimeInterface
    {
        return $this->date_envoi;
    }

    public function setDateEnvoi(\DateTimeInterface $date_envoi): self
    {
        $this->date_envoi = $date_envoi;

        return $this;
    }

    public function getUserReceiver(): ?User
    {
        return $this->userReceiver;
    }

    public function setUserReceiver(?User $userReceiver): self
    {
        $this->userReceiver = $userReceiver;

        return $this;
    }

    public function getUserSender(): ?User
    {
        return $this->userSender;
    }

    public function setUserSender(?User $userSender): self
    {
        $this->userSender = $userSender;

        return $this;
    }

    public function getConversation(): ?Conversation
    {
        return $this->conversation;
    }

    public function setConversation(?Conversation $conversation): self
    {
        $this->conversation = $conversation;

        return $this;
    }

    /**
     * @return Collection|ImageChat[]
     */
    public function getImageChats(): Collection
    {
        return $this->imageChats;
    }

    public function addImageChat(ImageChat $imageChat): self
    {
        if (!$this->imageChats->contains($imageChat)) {
            $this->imageChats[] = $imageChat;
            $imageChat->setMessage($this);
        }

        return $this;
    }

    public function removeImageChat(ImageChat $imageChat): self
    {
        if ($this->imageChats->contains($imageChat)) {
            $this->imageChats->removeElement($imageChat);
            // set the owning side to null (unless already changed)
            if ($imageChat->getMessage() === $this) {
                $imageChat->setMessage(null);
            }
        }

        return $this;
    }
}

src/Controller/ChatController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Message;
use App\Form\MessageType;
use App\Entity\Conversation;
use App\Entity\ImageChat;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\ConversationRepository;
use App\Repository\MessageRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class ChatController extends AbstractController
{
    /**
     * @Route("/profile/{id}/chat", name="chat")
     */
    public function chat($id, Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository, ConversationRepository $conversationRepository, MessageRepository $messageRepository)
    {
        // $userReceiver est l'utilisateur avec qui je chat, je récupère son id dans l'url 
        $userReceiver = $userRepository->find($id);
        // $userSender représente l'utilisateur connecté sur son appareil (moi)
        $userSender = $this->getUser();
        // je récupère l'id du sender 
        $userSenderId = $userSender->getId();
        // je récupère la conversation entre 2 utilisateurs   (moi et un autre)
        $conversation = $conversationRepository->findConv($id, $userSenderId);

        $message = new Message();

        // je génère un formulaire pour pouvoir envoyer un message
        $form = $this->createForm(MessageType::class, $message);

        // je recupere les données du formulaire message
        $form->handleRequest($request);
        // je vérifie si une conversation entre les deux utilisateur existe sinon  j'en crée une nouvelle
        if  ($conversation === null) {
        
            $conversation = new Conversation();

            // je set l'utilisateur qui recois le premier message
            $conversation->setUserReceiver($userReceiver);
            // je set l'utilisateur envoie le premier message
            $conversation->setUserSender($userSender);

            // j'enregistre ma conversation 
            $entityManager->persist($conversation);
            
        }
        // Je suis dans le cas où j'envoie les message donc je suis tjrs le sender et lui le receiver 
        // si les données sont valides
        if ($form->isSubmitted() && $form->isValid()) {
            
            // je récupère la conversation
            $message->setConversation($conversation);
            // je set la date et l'heure quand le message est envoyé
            $message->setDateEnvoi(new \DateTime());
            // je set le userSender (moi)
            $message->setUserSender($userSender);
            // je set le userReceiver (l'autre user)
            $message->setUserReceiver($userReceiver);

            // je procede a l'enregistrement de mes données messages
            $entityManager->persist($message);
        
            // je crée la variable $files qui est mes données entrer dans l'upload de fichier
            $files = $form->get('image')->getData();
           
            // si un ou des fichiers sont uploads alors je rentre dans la condition
            if ($files) {
                
                // je crée une boucle car mon ou mes images sont une collection
                foreach ($files as $file){
                    // je donne un nvx nom a mon fichier
                    $newFilename ='img_' . uniqid().'.'.$file->guessExtension();
                   
                    try {
                        // je déplace mon fichier ou je le souhaite
                        $file->move(
                            $this->getParameter('images_directory'),
                            $newFilename
                        );
                        
                    } catch (FileException $e) {
                       
                        // si erreur lors de l'envoie d'un fichier
                    }
                
                    // j'instancie une nouvelle image
                    $imageChat = new ImageChat();
                    // je set mon message lié a mon image
                    $imageChat->setMessage($message);
                    // je set le nouveau nom de mon fichier 
                    $imageChat->setImage($newFilename);
                    // jenregistre mon image 
                    $entityManager->persist($imageChat);
                    // je lie mon image a mon message
                    $message->addImageChat($imageChat);
                } 
               
            }
            
            // j'enregistre les données en BDD que si un fichier est upload ou le contenu est rempli  ou les deux
            if( $message->getContenu()!== null || !empty($file) ){
                
                $entityManager->flush();
            }
            
            return $this->redirectToRoute('chat', ['id' => $userReceiver->getId()]);
        } 
        
        // je récupère tous les messages lié a ma conversation récupérée au dessus grace au findConv() 
        $msg = $conversation->getMessages();
       
        
        return $this->render('chat/index.html.twig', [
            'formMessage' => $form->createView(),
            'messages' => $msg,
            'userReceiver' => $userReceiver,
            
        ]);
    }

     /**
     * @Route("/chat/{id}", name="messages")
     */
    public function messages($id, UserRepository $userRepository, ConversationRepository $conversationRepository)
    {
        // nouvelle fonction qui renvoie à une autre vue pour pouvoir rendre mon chat dynamique avec du ajax
        $userReceiver = $userRepository->find($id);
        $userSender =   $this->getUser();
        $userSenderId = $userSender->getId();
        $conversation = $conversationRepository->findConv($id, $userSenderId);

        // je récupère tous les messages lié a ma conversation 
        $msg = $conversation->getMessages();
        

        return $this->render('chat/messages.html.twig', [
            'messages' => $msg,
            'userReceiver' => $userReceiver,
            
            
        ]);
    }   
}

templates/chat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ChatController!{% endblock %}
         
{% block body %}
   <div class="mt-5 pt-4">
        <div class="container chat "> 
            <div class="row headerChat mb-5">
            {# rend le pseudo et l'image cliquable pour renvoyer sur le profil de l'autre utilisateur #}
            <a class="text-warning" href="{{path('profile_show', {'id': userReceiver.id}) }}">
                {# je récupère les données du user avec qui je chat  #}
                <img class="imageUserHeader ml-1" src="{{asset('uploads/image/' ~ userReceiver.image)}}" alt="">
                <h4 class="ml-3">{{userReceiver.pseudo}}</h4>
            </a>
            </div>
            
            {# j'appelle le fichier qui contient mes messages pour les remplacer toutes les 5 secondes pour un rechargement auto #}
            {% include 'chat/messages.html.twig' %}
            
            {# j'affiche mon formulaire de message  #}
            {{ form_start(formMessage)}}
                <div class="row">
                    <div class="col-8">
                        {{form_row(formMessage.contenu)}}
                    </div>
                    <div class="col-4">
                        {{form_row(formMessage.image)}}
                    </div>
                    
                </div>
            {{ form_end(formMessage)}}
        </div>
    </div>
    
    
{% endblock %}
{% block additionnalJS %}
    {# j'appelle ma fonction charger qui me sert a recharger mon chat toute les 5 secondes #}
    <script src="/js/chat.js"></script>
    <script> 
        charger({{ userReceiver.id }});
    </script>
{% endblock %}

templates/chat/messages.html.twig
<div id="chatMessages">
    {# je récupère une collection de messages liée à une conversation et je fais une boucle pour récupérer chaque message et les afficher un pas un #}
    {% for message in messages %}
    
    {# je vérifie si l'id du user avec qui je chat est le même que celui d'user qui envoie le message #}
    {# si oui alors l'autre user est celui qui envoie le message #}
    {% if userReceiver.id == message.userSender.id %}
    {# je crée des variables avec des valeurs différente d'affichage en fonction des messages envoyés et recus  #}
    {%  set classType = 'offset-1 msgRec' %}
    {% else %}
    {# si non je suis le user qui envoie le message #}
    {% set classType = 'offset-6 msgSend' %}
    {% endif %}
    
    <div class="row mb-3">
        {# j'appelle la variable contenant les valeurs en fonction du user qui a envoyé le message  #}
        <div class="col-5 {{classType}}  ">
            <div class="row">
                {# je récupère l'image de profile du user qui envoie le message et le pseudo de ce user  #}
                <img class="imageUserChat ml-1" src="{{asset('uploads/image/' ~ message.userSender.image)}}" alt="">
                <h6 class="ml-1 text-dark">{{message.userSender.pseudo}}</h6>
            </div>
            {# j'affiche le contenu du message #}
            <h4 class="contenuAntiDebordement">{{message.contenu}}</h4>
            
            {# j'affiche le ou les images lié au message  #}
            {% for image in message.imageChats %}
            
            
           
                <img class="imageChat" src="{{asset('uploads/image/' ~ image.image)}}" alt="">
            
            {% endfor %} <br>
            {# j'affiche la date d'envoie du message #}
            <small>envoyer le : {{message.dateEnvoi|date('d/m/Y H:i:s')}}</small>
        </div>
    </div>
    
    {% endfor %}
</div>